/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.ServicoDAO;
import Objetos.Mensagens;
import Objetos.Servico;
import Objetos.Usuario;
import java.awt.Graphics;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pablo
 */
public class servicos extends javax.swing.JPanel {

private int mode = 0;//0 = Cadastrar, 1 = Editar
private int id_edit = 0;//id para ajudar na edição
Mensagens m = new Mensagens();
    /**
     * Creates new form FrameCadastroCliente
     */
    public servicos() {
        initComponents();
        gerarTabela();
    }
    
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
    }
    
    public boolean camposPreenchidos(){
        boolean preenchidos = false;
        int qtd = 0;
        if(edValor.getText().trim().replaceAll(" ","").equals("")){
            qtd=qtd+1;
        }
        if(edTempo.getText().trim().replaceAll(" ","").equals("")){
            qtd=qtd+1;
        }
        if(edDesc.getText().trim().replaceAll(" ","").equals("")){
            qtd=qtd+1;
        }
        if(qtd!=0){
            preenchidos = false;
            if(qtd==1){
                JOptionPane.showMessageDialog(null, qtd+" campo ficou vazio!", "Importante", 1);
            }else{
                JOptionPane.showMessageDialog(null, qtd+" campos ficaram vazios!", "Importante", 1);
            }
        }else{
            preenchidos = true;
        }
        return preenchidos;
    }
    
    public void gerarTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaServicos.getModel();
        modelo.setNumRows(0);
        ServicoDAO pDAO = new ServicoDAO();
        List<Servico> Lista = pDAO.listarTodos();
        for(Servico p: Lista){     
            modelo.addRow(new Object[]{p.getId_servico(),p.getValor(),p.getTempo(),p.getDesc(),p.getId_funcionario_fk()});
        }
    }
    
    public void gerarTabela_com_Consulta(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaServicos.getModel();
        modelo.setNumRows(0);
        ServicoDAO pDAO = new ServicoDAO();
        List<Servico> Lista = pDAO.listarTodos();
        for(Servico p: Lista){     
            if((p.getDesc().toLowerCase()).contains(edPesquisa.getText().toLowerCase())||(String.valueOf(p.getId_servico()).contains(edPesquisa.getText().toLowerCase()))){
                modelo.addRow(new Object[]{p.getId_servico(),p.getValor(),p.getTempo(),p.getDesc(),p.getId_funcionario_fk()});
            }
        }
    }
    
    public void limparCampos(){
        edValor.setText(null);
        edTempo.setText(null);
        edDesc.setText(null);
    }
    
    public String alterarData(String data){
        String dia = data.substring(0, 1);
        String mes = data.substring(3, 4);
        String ano = data.substring(6, 9);
        String dataSQL = ano+"-"+mes+"-"+dia;
        return dataSQL;
    }
    
    public void trocarModo(Servico p){
        if(mode == 0){
            mode = 1;
            labelTitulo.setText("Editar Servico");
            btCadastrar.setText("Editar");
            btCancelarEdicao.setVisible(true);
            labelId.setText("ID:"+p.getId_servico());
            //Pegando valores dos EDs
            edValor.setText(String.valueOf(p.getValor()));
            edTempo.setText(String.valueOf(p.getTempo()));
            edDesc.setText(p.getDesc());
        }else{
            mode = 0;
            labelTitulo.setText("Cadastrar Servico");
            btCadastrar.setText("Cadastrar");
            btCancelarEdicao.setVisible(false);
            labelId.setText(null);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edDesc = new javax.swing.JTextField();
        edTempo = new javax.swing.JTextField();
        edValor = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btLimparCampos = new javax.swing.JButton();
        labelId = new javax.swing.JLabel();
        btCancelarEdicao = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        edPesquisa = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServicos = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Cadastrar Servicos");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 1030, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descrição:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 240, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tempo:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Valor:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 160, -1));

        edDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(edDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 290, 70));

        edTempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(edTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 165, 30));

        edValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(edValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 165, 30));

        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONE CADASTRAR DESPESA.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        btLimparCampos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONE LIMPAR CAMPOS.png"))); // NOI18N
        btLimparCampos.setText("Limpar Campos");
        btLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCamposActionPerformed(evt);
            }
        });
        add(btLimparCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, 39));

        labelId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 43, 13));

        btCancelarEdicao.setVisible(false);
        btCancelarEdicao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancelarEdicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONE LIMPAR CAMPOS.png"))); // NOI18N
        btCancelarEdicao.setText("Cancelar Edição");
        btCancelarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarEdicaoActionPerformed(evt);
            }
        });
        add(btCancelarEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 170, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Pesquisar:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        edPesquisa.setToolTipText("Pesquisa nos campos de descrição");
        add(edPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 220, 30));

        btPesquisar.setToolTipText("Pesquisa nos campos de descrição");
        btPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONE PESQUISAR.png"))); // NOI18N
        btPesquisar.setText("PESQUISAR");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, -1, -1));

        tabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Tempo", "Valor", "Id Funcionario"
            }
        ));
        jScrollPane1.setViewportView(tabelaServicos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        btAtualizar.setToolTipText("Editar o serviço selecionado.");
        btEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONE EDITAR.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 680, -1, -1));

        btAtualizar.setToolTipText("Atualiza a tabela.");
        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONE ATUALIZAR.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });
        add(btAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 680, -1, -1));

        btDeletar.setToolTipText("Deleta o serviço selecionado.");
        btDeletar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ICONE DELETAR.png"))); // NOI18N
        btDeletar.setText("Deletar");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });
        add(btDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 680, -1, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/projeto menu.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1400, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        if(camposPreenchidos()==true){
        Servico p = new Servico();
        ServicoDAO pDAO = new ServicoDAO();
        Usuario user = Usuario.getInstancia();
        //Pegando valores dos EDs
        p.setDesc(edDesc.getText());
        p.setTempo(edTempo.getText());
        p.setValor(Double.parseDouble(edValor.getText()));
        p.setId_funcionario_fk(user.getId());
        //Enviar para o DAO
        if(mode == 0){
            pDAO.cadastrarServico(p);
        }else{
            p.setId_servico(id_edit);
            pDAO.editarPorID(p);
            trocarModo(p);
        }
        gerarTabela();
        limparCampos();
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparCamposActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        gerarTabela_com_Consulta();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        if(tabelaServicos.getRowSelectionAllowed()==true){
            ServicoDAO pDAO = new ServicoDAO();
            DefaultTableModel modelo = (DefaultTableModel) tabelaServicos.getModel();
            int[] linhas = tabelaServicos.getSelectedRows();
            if(linhas.length==1){
                int id = Integer.parseInt(modelo.getValueAt(linhas[0], 0).toString());
                pDAO.deletar(id);
                gerarTabela();
            }else{
                m.mensagemPadrão1();
            }
        }else{
            m.mensagemPadrão2();
        }
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        gerarTabela();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if(tabelaServicos.getRowSelectionAllowed()==true){
            DefaultTableModel modelo = (DefaultTableModel) tabelaServicos.getModel();
            int[] linhas = tabelaServicos.getSelectedRows();
            if(linhas.length==1){
                int id = Integer.parseInt(modelo.getValueAt(linhas[0], 0).toString());
                ServicoDAO pDAO = new ServicoDAO();
                Servico p = new Servico();
                List<Servico> Lista = pDAO.listarTodos();
                for(int i=0;i<Lista.size();i++){
                    p = Lista.get(i);
                    if(p.getId_servico()==id){
                        id_edit = i;
                        trocarModo(p);
                    }
                }
            }else{
                m.mensagemPadrão1();
            }
        }else{
            m.mensagemPadrão2();
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btCancelarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarEdicaoActionPerformed
        Servico p = new Servico();
        trocarModo(p);
    }//GEN-LAST:event_btCancelarEdicaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelarEdicao;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btLimparCampos;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JTextField edDesc;
    private javax.swing.JTextField edPesquisa;
    private javax.swing.JTextField edTempo;
    private javax.swing.JTextField edValor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tabelaServicos;
    // End of variables declaration//GEN-END:variables
}
